Fix migration job

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -158,7 +158,7 @@ jobs:
              npm run test
       - save_cache:
           paths: [backend/node_modules]
-          key: backend-tes
+          key: backend-test
           
   scan-frontend:
     docker:
@@ -268,7 +268,6 @@ jobs:
              ansible-playbook -i inventory.txt configure-server.yml
       
       - destroy-environment
-      - revert-migrations
       
 
   run-migrations:
@@ -347,8 +346,49 @@ jobs:
       - destroy-environment
       - revert-migrations
 
+  smoke-test:
+    docker:
+      - image: cimg/base:stable
+    steps:
+      - checkout
+      - install_awscli
+      - install_nodejs
+      # Checkout code from git
+      - checkout
 
-
+      - run:
+          name: Get backend url
+          command: |
+            # your code here
+    - run:
+        name: Backend smoke test.
+        command: |
+            BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
+            --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+            --query 'Reservations[*].Instances[*].PublicIpAddress' \
+            --output text)
+    
+            export API_URL=http://${BACKEND_PUBLIC_IP}:3030
+            if curl -s $API_URL/api/status | grep "ok"
+            then
+                exit 0
+            else
+                exit 1
+            fi            
+      - run:
+          name: Frontend smoke test.
+          command: |
+              FRONTEND_WEBSITE=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com
+              if curl -s $FRONTEND_WEBSITE | grep "Welcome"
+              then
+                  exit 0
+              else
+                  exit 1
+              fi
+              
+      # Here's where you will add some code to rollback on failure  
+      - destroy-environment
+      - revert-migrations
           
 workflows:
   default:
@@ -374,3 +414,5 @@ workflows:
           requires: [configure-infrastructure]
       - deploy-frontend:
           requires: [run-migrations]
+      - smoke-test:
+          requires: [deploy-backend, deploy-frontend]
